spring:
  application:
    name: gateway-service

server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: http://localhost:8081
          predicates:
            - Path=/employees/**
        - id: department-service
          uri: http://localhost:8082
          predicates:
            - Path=/departments/**
